### ISSUE TITLE
[FE] Custom View Components

### ISSUE THREAD

**Issue by codeliner** [proophboard/cody-engine#10]
Cody generates View Components (table view, state view) into `packages/fe/src/app/components` and registers each component in the [views.ts](https://github.com/proophboard/cody-engine/blob/main/packages/fe/src/app/components/views.ts) registry file.

The [StandardPage](https://github.com/proophboard/cody-engine/blob/main/packages/fe/src/app/pages/standard-page.tsx#L31) uses the registry to import view components into the page by using the **value object name**.

A frontend developer should be able to **override** the default component generated by Cody. 

## Tasks
- [x] A developer should be able to add a custom view component in `packages/fe/src/lib/extensions/app/components` and registers that component in a `packages/fe/src/extensions/app/components/views.ts` registry file, similar to the one in the **main fe** package
- [x] Add an empty  `packages/fe/src/extensions/app/components/views.ts` registry file, be aware of the changes introduced in #3 
- [x] Write a helper function to load view components and use it in the `StandardPage` linked above
- [x] Place the helper function in `packages/fe/src/util/components`
- [x] The helper function should take a value object name as input and first check if a view component is registered with that name in the extensions views registry and if not check the views registry of the **main fe package**

## Related To
- #9

**Comment by codeliner** [comment]
@Juan-A-Jimenez not sure if you already started with the task? If yes, please rebase with latest main branch and be aware of the structural changes:

- we had to split the extension package and move directly into the main packages: `fe`, `be` and `shared`. Without that change it was not possible to run the production build due to circular dependencies
- I've updated the task description so that the paths are aligned with the new structure

**Comment by codeliner** [comment]
Closed by #38
