### ISSUE TITLE
[FE] Light and Dark theme

### ISSUE THREAD

**Issue by codeliner** [proophboard/cody-engine#2]
MUI theming has a light and a [dark mode](https://mui.com/material-ui/customization/dark-mode/). Light mode is enabled by default.

The old frontend app has a dark mode toggle in the topbar. You can find it here: https://github.com/event-engine/react-engine/blob/main/app/src/layout/TopBarMenu.tsx#L63

The current mode was stored in the global redux store, but in Cody Engine we don't use a redux store. As an alternative we can implement a [custom react hook](https://react.dev/learn/reusing-logic-with-custom-hooks) to get and set current theme mode from within any React component.

## Task

- [x] Add back the icon button in the topbar to toggle theme mode
- [x] Implement custom react hook to get and set theme mode
- [x] Use theme mode from react hook to change `theme.palette.mode` when user clicks the button in the topbar
