### ISSUE TITLE
[All] Improve contribution DX 

### ISSUE THREAD

**Issue by codeliner** [proophboard/cody-engine#3]
When someone wants to contribute to the project, they have to tell git to ignore a bunch of registry files, see [README](https://github.com/proophboard/cody-engine#contribution)

As an alternative, we could set up a script that is executed before server start up to check if those files are in place or have to be created. This would allow us to remove the files from the repository so that `prepare-contribution` can also add them along with `.gitignore` files.

We should not remove them completely, but rename them to: `[filename].ts.cetmpl`
The script can scan the repo for `*.ts.cetmpl` files and rename them back to normal ts files. So any new registry file will be handled by the script without maintaining an extra list :tada: 

## Tasks
- [x] Implement a script in [infrastructure/helpers](https://github.com/proophboard/cody-engine/tree/main/packages/infrastructure/src/lib/helpers) that can be executed with ts-node
- [x] The script should scan the repo for `*.ts.cetmpl` files and rename them back to normal ts files, if such a file does not exist alreay.
- [x] Remove all registry files from the repository
- [x] Make sure that the script is automatically executed on `npm run serve` command before server start

*Hint: You can change the [serve command](https://github.com/proophboard/cody-engine/blob/main/package.json#L6) in package.json to: `ts-node -r tsconfig-paths/register packages/infrastructure/src/lib/helpers/[name-of-script].ts && npx nx run-many -t serve`*

**Comment by kaitorched** [comment]
@codeliner in the repo, the existing "empty" *.ts registry files should be renamed to *.ts.cetmpl and not fully deleted, right? so that we have those templates to create the registry files when running npm serve for the first time

**Comment by codeliner** [comment]
@kaitorched yes, that's the idea :+1:
