### ISSUE TITLE
[FE] Custom Command Components

### ISSUE THREAD

**Issue by codeliner** [proophboard/cody-engine#9]
Cody generates Command Components (command button + modal) into `packages/fe/src/app/components` and registers each component in the [commands.ts](https://github.com/proophboard/cody-engine/blob/main/packages/fe/src/app/components/commands.ts) registry file.

The [StandardPage](https://github.com/proophboard/cody-engine/blob/main/packages/fe/src/app/pages/standard-page.tsx#L20) uses the registry to import command components into the action bar by using the **command name**.

A frontend developer should be able to **override** the default component generated by Cody. 

## Tasks
- [ ] A developer should be able to add a custom command component in `packages/fe/src/lib/extensions/app/components` and registers that component in a `packages/fe/src/lib/extensions/app/components/commands.ts` registry file, similar to the one in the **main fe** package
- [ ] Add an empty  `packages/fe/src/lib/extensions/app/components/commands.ts` registry file, be aware of the changes introduced in #3 
- [x] Write a helper function to load command components and use it in the `StandardPage` linked above
- [x] Place the helper function in `packages/fe/src/util/components`
- [x] The helper function should take a command name as input and first check if a command component is registered with that name in the extensions command registry and if not check the command registry of the **main fe package**

## Related To
- #10

**Comment by bofalke** [comment]
I guess the path `packages/fe/src/lib/extensions/` is now `packages/fe/src/extensions/` (missing `lib` folder) right? 

Or is the lib folder the one that will be used for customization and therefore created by the developer?
